"""revert resource_id to integer

Revision ID: cd4e24bed144
Revises: bb906134c8a6
Create Date: 2026-02-18 22:50:29.436403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4e24bed144'
down_revision: Union[str, Sequence[str], None] = 'bb906134c8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 既存のデータをクリアまたはNULLに設定
    op.execute('UPDATE audit_logs SET resource_id = NULL WHERE resource_id IS NOT NULL')
    # 型変更
    op.execute('ALTER TABLE audit_logs ALTER COLUMN resource_id TYPE INTEGER USING resource_id::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
